import type { ScheduleItem } from "@/types/schedule";

/** Programme minute par minute — source content-yuna-2026.md */
const STATIC_SCHEDULE: ScheduleItem[] = [
  {
    id: "s1-1",
    day: 1,
    time: "18:00 – 18:15",
    title: "Ouverture officielle et prière",
    description: null,
    order: 1,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
  {
    id: "s1-2",
    day: 1,
    time: "18:15 – 18:45",
    title: "Valère Kouton",
    description: null,
    order: 2,
    artist_id: null,
    artist_name: "Valère Kouton",
    artist_revealed: true,
  },
  {
    id: "s1-3",
    day: 1,
    time: "18:45 – 19:15",
    title: "NISTa Praise",
    description: null,
    order: 3,
    artist_id: null,
    artist_name: "NISTa Praise",
    artist_revealed: true,
  },
  {
    id: "s1-4",
    day: 1,
    time: "19:15 – 19:40",
    title: "Serviteur Pierre",
    description: null,
    order: 4,
    artist_id: null,
    artist_name: "Serviteur Pierre",
    artist_revealed: true,
  },
  {
    id: "s1-5",
    day: 1,
    time: "19:40 – 20:05",
    title: "David Okit",
    description: null,
    order: 5,
    artist_id: null,
    artist_name: "David Okit",
    artist_revealed: true,
  },
  {
    id: "s1-6",
    day: 1,
    time: "20:05 – 20:50",
    title: "Parole : Prophète Johnny Doefia",
    description: "Message prophétique · 45 min",
    order: 6,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
  {
    id: "s1-7",
    day: 1,
    time: "20:50 – 21:50",
    title: "Simiane Tatu, Adoration",
    description: "Temps fort · 1h",
    order: 7,
    artist_id: null,
    artist_name: "Simiane Tatu",
    artist_revealed: true,
  },
  {
    id: "s1-8",
    day: 1,
    time: "21:50 – 22:35",
    title: "Exo Éclats",
    description: null,
    order: 8,
    artist_id: null,
    artist_name: "Exo Éclats",
    artist_revealed: true,
  },
  {
    id: "s1-9",
    day: 1,
    time: "22:35 – 23:00",
    title: "Clôture et annonces du dimanche",
    description: null,
    order: 9,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
  {
    id: "s2-1",
    day: 2,
    time: "18:00 – 18:10",
    title: "Ouverture et prière",
    description: null,
    order: 1,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
  {
    id: "s2-2",
    day: 2,
    time: "18:10 – 18:30",
    title: "David Track",
    description: null,
    order: 2,
    artist_id: null,
    artist_name: "David Track",
    artist_revealed: true,
  },
  {
    id: "s2-3",
    day: 2,
    time: "18:30 – 18:50",
    title: "Minister Glory",
    description: null,
    order: 3,
    artist_id: null,
    artist_name: "Minister Glory",
    artist_revealed: true,
  },
  {
    id: "s2-4",
    day: 2,
    time: "18:50 – 19:20",
    title: "Prophète Dr Hervé Mama, Exhortation",
    description: "30 min",
    order: 4,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
  {
    id: "s2-5",
    day: 2,
    time: "19:20 – 20:20",
    title: "Derek Jones, Adoration",
    description: "Temps fort · 1h",
    order: 5,
    artist_id: null,
    artist_name: "Derek Jones",
    artist_revealed: true,
  },
  {
    id: "s2-6",
    day: 2,
    time: "20:20 – 21:20",
    title: "Parole : Joël Francis Tatu",
    description: "1h",
    order: 6,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
  {
    id: "s2-7",
    day: 2,
    time: "21:20 – 22:20",
    title: "Joe Mettle",
    description: "Tête d'affiche internationale · 1h",
    order: 7,
    artist_id: null,
    artist_name: "Joe Mettle",
    artist_revealed: true,
  },
  {
    id: "s2-8",
    day: 2,
    time: "22:20 – 22:30",
    title: "Clôture et envoi",
    description: null,
    order: 8,
    artist_id: null,
    artist_name: null,
    artist_revealed: false,
  },
];

export async function getSchedule(): Promise<ScheduleItem[]> {
  return STATIC_SCHEDULE;
}
